Template with Django/accounts/urls.py
from django.urls import path
from accounts.views import accounts

app_name='accounts'

urlpatterns = [
    path('', accounts,name='accounts'),
]

Template with Django/bank/urls.py
from django.urls import path
from .views import bank
app_name='bank'

urlpatterns = [    
    path('', bank,name='bank'),
]

Template with Django/blogs/urls.py
from django.urls import path
from blogs.views import blogs ,blog_detail

app_name='blogs'

urlpatterns = [
    path('', blogs,name='blogs'),
    path('<str:name>',blog_detail,name='blog-detail')
]

Template with Django/contact/urls.py
from django.urls import path
from .views import contact

app_name='contact'

urlpatterns = [
    path('', contact,name='contact'),
]

Template with Django/core/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('start.urls',namespace='start')),
    path('blog/', include('blogs.urls',namespace='blogs')),
    path('account/', include('accounts.urls',namespace='accounts')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('bank/', include('bank.urls',namespace='bank')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Template with Django/start/urls.py
from django.urls import path
from start.views import start

app_name='start'

urlpatterns = [
    path('', start,name='start'),
]

Template with Django/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

class User(AbstractUser):
    email = models.EmailField(_('email address'), blank=True, unique=True)
    bio = models.TextField(blank=True, null=True, help_text='Give some information about yourself')
    image = models.ImageField(upload_to='users/', blank=True, null=True)
    first_name = models.CharField(_('first name'), max_length=150, blank=True, db_index=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'username','image']
    
    @property
    def user_image(self):
        if self.image:
            return self.image
        return 'https://www.pngfind.com/pngs/m/470-4703547_icon-user-icon-hd-png-download.png'

Template with Django/bank/models.py
from django.db import models

class Bank(models.Model): 
    name=models.CharField(max_length=100,blank=False,null=False)
    owner=models.CharField(max_length=100,blank=False,null=False)
    # Relations
    def __str__(self):
        return self.name

class Filial(models.Model):
    adress=models.CharField(max_length=100,blank=False,null=False)
    customer=models.IntegerField(blank=False,null=False)
    bank=models.ForeignKey(Bank,on_delete=models.CASCADE,related_name="b")
    
    def __str__(self):
        return self.adress

Template with Django/blogs/models.py
from django.db import models

class Blog(models.Model):
    title=models.CharField(max_length=100,blank=False,null=False)
    author=models.CharField(max_length=100,blank=False,null=False)
    date=models.DateTimeField(auto_now=True)


def __str__(self) :
        return self.title
    
class Meta:
    verbose_name='Blog'
    verbose_name_plural='Blogs'

Template with Django/contact/models.py
from django.db import models

class Contact(models.Model):
    fname=models.CharField(max_length=100,blank=False,null=False)
    lname=models.CharField(max_length=100,blank=False,null=False)
    email=models.EmailField()
    comment=models.TextField()
    date=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.fname} {self.lname}'s comment"
        
    class Meta:
        verbose_name='Contact'
        verbose_name_plural='Contacts'

Template with Django/start/models.py
from django.db import models

# Create your models here.

Template with Django/contact/forms.py
from wsgiref.validate import validator
from django import forms
from django.forms import ModelForm, ValidationError
from contact.models import Contact
from django import forms

class ContactForm(ModelForm):
    
    class Meta:
        model = Contact
        fields = '__all__'

        widgets = {
            'fname': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'first name...',
                }
            ),

            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'email...'
            }),

            'lname': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'last name...'
            }),

            'comment': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'message here...'
            }),
        }    

    def clean_fname(self):
        fname = self.cleaned_data['fname']
        if not fname.istitle():
            raise ValidationError('This is not valid first name')
        return fname

    def clean_lname(self):
        lname = self.cleaned_data['lname']
        if not lname.istitle():
            raise ValidationError('This is not valid last name')
        return lname
    
    def clean_comment(self):
        comment = self.cleaned_data['comment']
        if not len(comment)>10:
            raise ValidationError('This messsage is short')
        return comment

    def clean_email(self):
        email = self.cleaned_data['email']
        if not email.endswith('gmail.com'):
            raise ValidationError('Only gmail.com emails are accepted')
        return email
    

Template with Django/accounts/views.py
from django.shortcuts import render

def accounts(request):
    return render(request,'accounts/accounts.html')

Template with Django/bank/views.py
from django.shortcuts import render
from . models import Bank,Filial
def bank(request):
    bank=Bank.objects.all().first()
    filials=Filial.objects.all()
    context={
        'bank':bank,
        'filials':filials,
    }
    return render(request,'bank/bank.html',context=context)

Template with Django/blogs/views.py
from django.shortcuts import render
from blogs.models import Blog

def blogs(request):
    blogs=Blog.objects.all()
    context={
        'blogs':blogs
    }
    return render(request,'blogs/blogs.html',context=context)

def blog_detail(request,name):
    blogs=Blog.objects.all()
    blog=blogs.filter(title=name).first()
    context={
        'blog':blog
    }
    return render(request,'blogs/blog_detail.html',context=context)

Template with Django/contact/views.py
from django.shortcuts import render,redirect
from . models import Contact
from .forms import ContactForm
from django.urls import reverse
from django.contrib import messages

def contact(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message has been received!')
            return redirect(reverse('contact:contact'))

    return render(request, 'contact/contact.html', {'form': form})

    # if request.method == 'POST':
    #     Contact.objects.create(
    #         fname=request.POST.get('fname'),
    #         lname=request.POST.get('lname'),
    #         email=request.POST.get('email'),
    #         comment=request.POST.get('comment'),
    #     )
    #     return redirect('contact:contact')

Template with Django/start/views.py
from django.shortcuts import render

def start(request):
    return render(request,'start/index.html')

Template with Django/templates/accounts/accounts.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<h1 style="    margin-top: 60px;display: flex;justify-content: center;">Welcome Accounts Page</h1>
<table style="margin-top: 40px;margin-bottom: 385px;
" class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Fullname</th>
        <th scope="col">Position</th>
        <th scope="col">Salary</th>
        <th scope="col">Picture</th>
      </tr>
    </thead>
    <tbody>
      {% for account in accounts %}
      <tr>
        <td>{{account.fullname}}</td>
        <td>{{account.department}}</td>
        <td>{{account.salary}} $</td>
        <td><img src="{{account.profilpicture.url}}" alt="" height="50px" weight="50px"></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

Template with Django/templates/bank/bank.html
Bank name : {{bank.name}}
<br><br>
Bank owner : {{bank.owner}}
<br><br>
{% for f in filials %}
{{f.bank.owner}}
<br>
{% endfor %}
{{bank.b}}

Template with Django/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel=”stylesheet” href=”https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css”rel=”nofollow” integrity=”sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm” crossorigin=”anonymous”>
<link rel=”stylesheet” href=”https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css”rel=”nofollow” integrity=”sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I” crossorigin=”anonymous”>
<style>
body {font-family: "Lato", sans-serif}
.mySlides {display: none}
</style>
</head>
<body>

  {% block content %} {% endblock %}

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a href="{% url 'start:start' %}" class="w3-bar-item w3-button w3-padding-large">HOME</a>
    <a href="{% url 'blogs:blogs' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Blog</a>
    <a href="{% url 'accounts:accounts' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Account</a>
    <a href="{% url 'contact:contact' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Contact</a>
    <a href="{% url 'bank:bank' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Bank</a>
    <a href="javascript:void(0)" class="w3-padding-large w3-hover-red w3-hide-small w3-right"><i class="fa fa-search"></i></a>
  </div>
</div>

<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->
<div id="navDemo" class="w3-bar-block w3-black w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:40px">
  <a href="#band" class="w3-bar-item w3-button w3-padding-medium" onclick="myFunction()">BAND</a>
  <a href="#tour" class="w3-bar-item w3-button w3-padding-medium" onclick="myFunction()">TOUR</a>
  <a href="#contact" class="w3-bar-item w3-button w3-padding-medium" onclick="myFunction()">CONTACT</a>
</div>


<!-- Footer -->
<footer class="w3-container w3-padding-40 w3-center w3-opacity w3-light-grey w3-xlarge">
  <p class="w3-medium">  
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
    Powered by Turyan Azizov
</p>
</footer>

</body>
</html>

Template with Django/templates/blogs/blog_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div style="    display: flex;
justify-content: space-evenly;
align-items: center;
margin-top: 270px;
margin-bottom: 315px;">
    <h1>Book details :</h1>
    <br>
    Author : {{blog.author}}
    <br>
    Title : {{blog.title}}
    <br>
    Date : {{blog.date}}
    <br>
    <br>
    <a style="background-color:crimson;" href="{% url 'blogs:blogs' %}">Go Blogs page</a>
</div>



{% endblock %}

Template with Django/templates/blogs/blogs.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div style="display: flex;justify-content:center;margin-top:50px">

<div>
<h2>All Books</h2>
{% for blog in blogs %}
<h3><a href="{% url 'blogs:blog-detail' blog.title %}">{{blog.title}}</a></h3>
{% endfor %}
</div>

</div>
<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:12px">


    <!-- The Band Section -->
    <div class="w3-container w3-content w3-center w3-padding-50" style="max-width:800px" id="band">
      
      <div class="w3-row w3-padding-20">
        <div class="w3-third">
          <p>Photo 1</p>
          <img src="{% static 'start/images/photo-1531804055935-76f44d7c3621.jfif' %}" class="w3-round w3-margin-bottom" alt="Random Name" style="width:60%">
        </div>
        <div class="w3-third">
          <p>Photo 2</p>
          <img src="{% static 'start/images/photo-1531804055935-76f44d7c3621.jfif' %}" class="w3-round w3-margin-bottom" alt="Random Name" style="width:60%">
        </div>
        <div class="w3-third">
          <p>Photo 3</p>
          <img src="{% static 'start/images/photo-1531804055935-76f44d7c3621.jfif' %}" class="w3-round" alt="Random Name" style="width:60%">
        </div>
      </div>
    </div>
  

{% endblock %}

Template with Django/templates/contact/contact.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<!--Section: Contact v.2-->
<link rel="stylesheet" href="/static/contact/style.css">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container contact" style="margin-bottom: 320px;">
	<div class="row">
		<div class="col-md-3">
			<div class="contact-info">
				<img src="https://image.ibb.co/kUASdV/contact-image.png" alt="image" />
				<h2>Contact Us</h2>
				<h4>We would love to hear from you !</h4>
			</div>
		</div>
		<div class="col-md-9">
			<div class="contact-form">
				<form method="POST">
					{% csrf_token %}

					{% for field in form %}
					<div class="form-group">
						<div class="col-sm-10">
							{{field}}
						</div>
					</div>
					{% for error in field.errors %}
                                <li class="alert alert-danger"> {{error}} </li>
                            {% endfor %}
					{% endfor %}
					
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-default">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock %}

Template with Django/templates/start/index.html
{% extends 'base/base.html' %}
{% block content %}

<h1 style="display: flex;margin-top: 330px;margin-bottom: 315px;align-items: center;justify-content: center;">Welcome My First Django Template</h1>

{% endblock %}